# Generated by Django 5.2.6 on 2025-09-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('users', '0002_customuser_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hotels.hotel', verbose_name='Отель'),
        ),
    ]
