# Generated by Django 5.2.6 on 2025-09-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0003_customuser_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rooms.room', verbose_name='Номер'),
        ),
    ]
