# Generated by Django 5.2.6 on 2025-09-08 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('family', 'Family Room'), ('superior', 'Superior Room'), ('deluxe', 'Deluxe Room'), ('studio', 'Studio'), ('suite', 'Suite'), ('junior', 'Junior Suite'), ('residence', 'Residence'), ('royal', 'Royal Suite'), ('penthouse', 'Penthouse')], default='standard', max_length=15, verbose_name='Тип номера')),
                ('adults', models.PositiveSmallIntegerField(default=0, verbose_name='Количество проживающих взрослых')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Количество проживающих детей')),
                ('area', models.PositiveSmallIntegerField(default=25, verbose_name='Площадь, м²')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество номеров этой категории')),
                ('double_bed', models.IntegerField(blank=True, help_text='Двуспальная кровать', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Двуспальная кровать')),
                ('single_bed', models.IntegerField(blank=True, help_text='Односпальная кровать', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Односпальная кровать')),
                ('meal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='meals.mealtype', verbose_name='Тип питания')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(choices=[('general', 'Общие'), ('coffee', 'Кофе-станция'), ('bathroom', 'В ванной комнате'), ('view', 'Вид')], default='general', max_length=15, verbose_name='Тип удобств')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Удобства номера',
                'verbose_name_plural': 'Удобства номера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_photos/')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Фотография номера',
                'verbose_name_plural': 'Фотографии номера',
                'ordering': ['room__id'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_choice', models.CharField(choices=[('yes', 'Разрешено'), ('no', 'Запрещено')], default='no', max_length=15, verbose_name='Правило')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Правило номера',
                'verbose_name_plural': 'Правила номера',
                'ordering': ['name'],
            },
        ),
    ]
