# Generated by Django 5.2.6 on 2025-09-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_single', models.BooleanField(default=False, verbose_name='Односпальная кровать')),
                ('single_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество односпальных кроватей')),
                ('has_double', models.BooleanField(default=False, verbose_name='Двуспальная кровать')),
                ('double_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество двуспальных кроватей')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('family', 'Family Room'), ('superior', 'Superior Room'), ('deluxe', 'Deluxe Room'), ('studio', 'Studio'), ('suite', 'Suite'), ('junior', 'Junior Suite'), ('residence', 'Residence'), ('royal', 'Royal Suite'), ('penthouse', 'Penthouse')], default='standard', max_length=15, verbose_name='Тип номера')),
                ('adults', models.PositiveSmallIntegerField(default=0, verbose_name='Количество проживающих взрослых')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Количество проживающих детей')),
                ('area', models.PositiveSmallIntegerField(default=25, verbose_name='Площадь, м²')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество номеров этой категории')),
                ('beds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.bed')),
                ('meal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='food.mealtype', verbose_name='Тип питания')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Общие')),
                ('wifi', models.BooleanField(default=False, verbose_name='Бесплатный Wi-Fi')),
                ('sofa', models.BooleanField(default=False, verbose_name='Диван')),
                ('conditioner', models.BooleanField(default=False, verbose_name='Кондиционер')),
                ('heating', models.BooleanField(default=False, verbose_name='Отопление')),
                ('beds', models.BooleanField(default=False, verbose_name='Удобные кровати')),
                ('tv', models.BooleanField(default=False, verbose_name='Телевизор')),
                ('dinnertable', models.BooleanField(default=False, verbose_name='Обеденный стол')),
                ('kitchen', models.BooleanField(default=False, verbose_name='Кухня')),
                ('worktable', models.BooleanField(default=False, verbose_name='Рабочий стол')),
                ('wardrobe', models.BooleanField(default=False, verbose_name='Шкаф или гардероб')),
                ('bar', models.BooleanField(default=False, verbose_name='Мини-бар')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkingAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кофе-станция')),
                ('teapot', models.BooleanField(default=False, verbose_name='Электрический чайник')),
                ('coffee', models.BooleanField(default=False, verbose_name='Кофемашина')),
                ('tea', models.BooleanField(default=False, verbose_name='Чай/кофе')),
                ('dishes', models.BooleanField(default=False, verbose_name='Посуда')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='CustomViewAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбрано')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='CustomGeneralAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбрано')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDrinkingAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбрано')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBathroomAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбрано')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='BathroomAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='В ванной комнате')),
                ('bath', models.BooleanField(default=False, verbose_name='Ванна')),
                ('shower', models.BooleanField(default=False, verbose_name='Душ')),
                ('bidet', models.BooleanField(default=False, verbose_name='Биде')),
                ('jakuzzi', models.BooleanField(default=False, verbose_name='Джакузи')),
                ('fan', models.BooleanField(default=False, verbose_name='Фен')),
                ('bathrobe', models.BooleanField(default=False, verbose_name='Халат')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_photos/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_choice', models.CharField(choices=[('yes', 'Разрешено'), ('no', 'Запрещено')], default='no', max_length=15, verbose_name='Правило')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='ViewAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид')),
                ('sea', models.BooleanField(default=False, verbose_name='На море')),
                ('pool', models.BooleanField(default=False, verbose_name='На бассейн')),
                ('park', models.BooleanField(default=False, verbose_name='На парк')),
                ('sight', models.BooleanField(default=False, verbose_name='На достопримечательности')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
