# Generated by Django 5.2.6 on 2025-09-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroomamenities',
            options={'ordering': ['name'], 'verbose_name': 'В ванной комнате', 'verbose_name_plural': 'В ванной комнате'},
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['id'], 'verbose_name': 'Кровати', 'verbose_name_plural': 'Кровати'},
        ),
        migrations.AlterModelOptions(
            name='custombathroomamenities',
            options={'ordering': ['name'], 'verbose_name': 'Дополнительные удобства в ванной комнате', 'verbose_name_plural': 'Дополнительные удобства в ванной комнате'},
        ),
        migrations.AlterModelOptions(
            name='customdrinkingamenities',
            options={'ordering': ['name'], 'verbose_name': 'Дополнительные удобства напитков', 'verbose_name_plural': 'Дополнительные удобства напитков'},
        ),
        migrations.AlterModelOptions(
            name='customgeneralamenities',
            options={'ordering': ['name'], 'verbose_name': 'Дополнительные удобства', 'verbose_name_plural': 'Дополнительные удобства'},
        ),
        migrations.AlterModelOptions(
            name='customviewamenities',
            options={'ordering': ['name'], 'verbose_name': 'Дополнительные удобства вида', 'verbose_name_plural': 'Дополнительные удобства вида'},
        ),
        migrations.AlterModelOptions(
            name='drinkingamenities',
            options={'ordering': ['name'], 'verbose_name': 'Кофе-станция', 'verbose_name_plural': 'Кофе-станция'},
        ),
        migrations.AlterModelOptions(
            name='generalamenities',
            options={'ordering': ['name'], 'verbose_name': 'Общие удобства', 'verbose_name_plural': 'Общие удобства'},
        ),
        migrations.AlterModelOptions(
            name='roomphoto',
            options={'ordering': ['room__id'], 'verbose_name': 'Фотография номера', 'verbose_name_plural': 'Фотографии номера'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name'], 'verbose_name': 'Правило номера', 'verbose_name_plural': 'Правила номера'},
        ),
        migrations.AlterModelOptions(
            name='viewamenities',
            options={'ordering': ['name'], 'verbose_name': 'Вид', 'verbose_name_plural': 'Вид'},
        ),
    ]
