# Generated by Django 5.2.6 on 2025-09-07 16:03

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта для расстояния',
                'verbose_name_plural': 'Типы объектов для расстояния',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralComfortType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, help_text='Загрузите изображение иконки', null=True, upload_to='comfort_icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Вид основных удобств',
                'verbose_name_plural': 'Виды основных удобств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа отдыха')),
            ],
            options={
                'verbose_name': 'Тип отдыха',
                'verbose_name_plural': 'Типы отдыха',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Расстояние (м)')),
                ('distance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='hotels.distancetype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Расстояние',
                'verbose_name_plural': 'Расстояния',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название отеля')),
                ('hotel_type', models.CharField(choices=[('hotel', 'Отель'), ('hostel', 'Хостел'), ('villa', 'Вилла'), ('apartment', 'Апартаменты'), ('guest', 'Гостевой дом')], default='hotel', max_length=100, verbose_name='Тип отеля')),
                ('category', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Категория')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('check_in_time', models.TimeField(default=datetime.time(14, 0), verbose_name='Заселение')),
                ('check_out_time', models.TimeField(default=datetime.time(12, 0), verbose_name='Выезд')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('distances', models.ManyToManyField(blank=True, null=True, related_name='hotels', to='hotels.distance', verbose_name='Расстояния')),
                ('general_comfort', models.ManyToManyField(blank=True, null=True, related_name='hotels', to='hotels.generalcomforttype', verbose_name='Основные удобства')),
                ('vacation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='hotels.vacationtype', verbose_name='Тип отдыха')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_selected', models.BooleanField(default=False)),
                ('amenity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotels.amenitytype')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotels.hotel', verbose_name='Отель')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_photos/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hotels.hotel')),
            ],
        ),
    ]
