# Generated by Django 5.2.6 on 2025-09-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name': 'Особые удобства', 'verbose_name_plural': 'Особые удобства'},
        ),
        migrations.AlterModelOptions(
            name='amenitytype',
            options={'ordering': ['name'], 'verbose_name': 'Вид особых удобств', 'verbose_name_plural': 'Виды особых удобств'},
        ),
        migrations.AlterModelOptions(
            name='distance',
            options={'ordering': ['id'], 'verbose_name': 'Расстояние', 'verbose_name_plural': 'Расстояния'},
        ),
        migrations.AlterModelOptions(
            name='hotelphoto',
            options={'ordering': ['hotel__id'], 'verbose_name': 'Фотография отеля', 'verbose_name_plural': 'Фотографии отеля'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name'], 'verbose_name': 'Правило отеля', 'verbose_name_plural': 'Правила отеля'},
        ),
    ]
