# Generated by Django 5.2.6 on 2025-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('No meal', 'Без питания'), ('breakfast', 'Завтрак'), ('breakfast_dinner', 'Завтрак и ужин'), ('full', 'Полный пансион'), ('all', 'All inclusive'), ('ultra', 'Ultra All inclusive')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
