# Generated by Django 5.2.6 on 2025-09-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ['id'], 'verbose_name': 'Тип питания', 'verbose_name_plural': 'Типы питания'},
        ),
    ]
