VACATION_TYPE_MAX_LENGTH: int = 100
HOTEL_MAX_LENGTH: int = 100
HOTEL_TYPE_MAX_LENGTH: int = 100
CITY_MAX_LENGTH: int = 200
ADDRESS_MAX_LENGTH: int = 500
DISTANCE_TYPE_MAX_LENGTH: int = 100
NAME_MAX_LENGTH: int = 100
AMENITY_TYPE_MAX_LENGTH: int = 20
